# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CamDisplay_ui.ui'
#
# Created: Mon Dec  8 08:07:39 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CamDisplayMW(object):
    def setupUi(self, CamDisplayMW):
        CamDisplayMW.setObjectName(_fromUtf8("CamDisplayMW"))
        CamDisplayMW.resize(800, 600)
        self.centralwidget = QtGui.QWidget(CamDisplayMW)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color:rgb(176,224,230)"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.ClockDisplay = QtGui.QLabel(self.centralwidget)
        self.ClockDisplay.setGeometry(QtCore.QRect(120, 70, 340, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ClockDisplay.setFont(font)
        self.ClockDisplay.setStyleSheet(_fromUtf8("background-color:rgb(200,226,255); color: rgb(0, 0,0)"))
        self.ClockDisplay.setFrameShape(QtGui.QFrame.Panel)
        self.ClockDisplay.setFrameShadow(QtGui.QFrame.Raised)
        self.ClockDisplay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ClockDisplay.setObjectName(_fromUtf8("ClockDisplay"))
        self.Cam1Name = QtGui.QLabel(self.centralwidget)
        self.Cam1Name.setGeometry(QtCore.QRect(120, 292, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cam1Name.setFont(font)
        self.Cam1Name.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.Cam1Name.setFrameShape(QtGui.QFrame.Panel)
        self.Cam1Name.setFrameShadow(QtGui.QFrame.Raised)
        self.Cam1Name.setObjectName(_fromUtf8("Cam1Name"))
        self.RecordingPathName1 = QtGui.QLabel(self.centralwidget)
        self.RecordingPathName1.setGeometry(QtCore.QRect(210, 292, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RecordingPathName1.setFont(font)
        self.RecordingPathName1.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.RecordingPathName1.setFrameShape(QtGui.QFrame.Panel)
        self.RecordingPathName1.setFrameShadow(QtGui.QFrame.Raised)
        self.RecordingPathName1.setObjectName(_fromUtf8("RecordingPathName1"))
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(670, 500, 98, 27))
        self.quitButton.setStyleSheet(_fromUtf8("background-color:rgb(200,224,255);color:rgb(0,0,0)"))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.MetadataDisplay = QtGui.QPlainTextEdit(self.centralwidget)
        self.MetadataDisplay.setGeometry(QtCore.QRect(120, 130, 520, 125))
        self.MetadataDisplay.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.MetadataDisplay.setReadOnly(True)
        self.MetadataDisplay.setObjectName(_fromUtf8("MetadataDisplay"))
        self.AltitudeDisplay = QtGui.QLabel(self.centralwidget)
        self.AltitudeDisplay.setGeometry(QtCore.QRect(470, 70, 90, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AltitudeDisplay.setFont(font)
        self.AltitudeDisplay.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)\n"
""))
        self.AltitudeDisplay.setFrameShape(QtGui.QFrame.Panel)
        self.AltitudeDisplay.setFrameShadow(QtGui.QFrame.Raised)
        self.AltitudeDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AltitudeDisplay.setObjectName(_fromUtf8("AltitudeDisplay"))
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(410, 500, 98, 27))
        self.startButton.setStyleSheet(_fromUtf8("background-color:rgb(200,224,255);color:rgb(0,0,0)"))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(540, 500, 98, 27))
        self.stopButton.setStyleSheet(_fromUtf8("background-color:rgb(200,224,255);color:rgb(0,0,0)"))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.clockLabeler = QtGui.QLabel(self.centralwidget)
        self.clockLabeler.setGeometry(QtCore.QRect(120, 54, 62, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.clockLabeler.setFont(font)
        self.clockLabeler.setTextFormat(QtCore.Qt.PlainText)
        self.clockLabeler.setObjectName(_fromUtf8("clockLabeler"))
        self.altimeterChoice = QtGui.QLabel(self.centralwidget)
        self.altimeterChoice.setGeometry(QtCore.QRect(570, 70, 66, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.altimeterChoice.setFont(font)
        self.altimeterChoice.setStyleSheet(_fromUtf8("background-color:rgb(255,255,255);color:rgb(0,0,0)"))
        self.altimeterChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.altimeterChoice.setObjectName(_fromUtf8("altimeterChoice"))
        self.dopplerChoice = QtGui.QLabel(self.centralwidget)
        self.dopplerChoice.setGeometry(QtCore.QRect(570, 96, 66, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dopplerChoice.setFont(font)
        self.dopplerChoice.setStyleSheet(_fromUtf8("background-color:rgb(255,255,255);color:rgb(0,0,0)"))
        self.dopplerChoice.setTextFormat(QtCore.Qt.PlainText)
        self.dopplerChoice.setAlignment(QtCore.Qt.AlignCenter)
        self.dopplerChoice.setObjectName(_fromUtf8("dopplerChoice"))
        self.altitudeLabeler = QtGui.QLabel(self.centralwidget)
        self.altitudeLabeler.setGeometry(QtCore.QRect(510, 54, 66, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.altitudeLabeler.setFont(font)
        self.altitudeLabeler.setTextFormat(QtCore.Qt.PlainText)
        self.altitudeLabeler.setObjectName(_fromUtf8("altitudeLabeler"))
        self.metaLabeler = QtGui.QLabel(self.centralwidget)
        self.metaLabeler.setGeometry(QtCore.QRect(120, 116, 66, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.metaLabeler.setFont(font)
        self.metaLabeler.setTextFormat(QtCore.Qt.PlainText)
        self.metaLabeler.setObjectName(_fromUtf8("metaLabeler"))
        self.camSectionLabel = QtGui.QLabel(self.centralwidget)
        self.camSectionLabel.setGeometry(QtCore.QRect(120, 268, 66, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.camSectionLabel.setFont(font)
        self.camSectionLabel.setTextFormat(QtCore.Qt.PlainText)
        self.camSectionLabel.setObjectName(_fromUtf8("camSectionLabel"))
        self.recordChoice1 = QtGui.QLabel(self.centralwidget)
        self.recordChoice1.setGeometry(QtCore.QRect(500, 292, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.recordChoice1.setFont(font)
        self.recordChoice1.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.recordChoice1.setAlignment(QtCore.Qt.AlignCenter)
        self.recordChoice1.setObjectName(_fromUtf8("recordChoice1"))
        self.idleChoice1 = QtGui.QLabel(self.centralwidget)
        self.idleChoice1.setGeometry(QtCore.QRect(500, 310, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.idleChoice1.setFont(font)
        self.idleChoice1.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.idleChoice1.setAlignment(QtCore.Qt.AlignCenter)
        self.idleChoice1.setObjectName(_fromUtf8("idleChoice1"))
        self.RecordingPathName2 = QtGui.QLabel(self.centralwidget)
        self.RecordingPathName2.setGeometry(QtCore.QRect(210, 340, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.RecordingPathName2.setFont(font)
        self.RecordingPathName2.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.RecordingPathName2.setFrameShape(QtGui.QFrame.Panel)
        self.RecordingPathName2.setFrameShadow(QtGui.QFrame.Raised)
        self.RecordingPathName2.setObjectName(_fromUtf8("RecordingPathName2"))
        self.Cam2Name = QtGui.QLabel(self.centralwidget)
        self.Cam2Name.setGeometry(QtCore.QRect(120, 340, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cam2Name.setFont(font)
        self.Cam2Name.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.Cam2Name.setFrameShape(QtGui.QFrame.Panel)
        self.Cam2Name.setFrameShadow(QtGui.QFrame.Raised)
        self.Cam2Name.setObjectName(_fromUtf8("Cam2Name"))
        self.recordChoice2 = QtGui.QLabel(self.centralwidget)
        self.recordChoice2.setGeometry(QtCore.QRect(500, 340, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.recordChoice2.setFont(font)
        self.recordChoice2.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.recordChoice2.setAlignment(QtCore.Qt.AlignCenter)
        self.recordChoice2.setObjectName(_fromUtf8("recordChoice2"))
        self.idleChoice2 = QtGui.QLabel(self.centralwidget)
        self.idleChoice2.setGeometry(QtCore.QRect(500, 360, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.idleChoice2.setFont(font)
        self.idleChoice2.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.idleChoice2.setAlignment(QtCore.Qt.AlignCenter)
        self.idleChoice2.setObjectName(_fromUtf8("idleChoice2"))
        self.Cam3Name = QtGui.QLabel(self.centralwidget)
        self.Cam3Name.setGeometry(QtCore.QRect(120, 390, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Cam3Name.setFont(font)
        self.Cam3Name.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.Cam3Name.setFrameShape(QtGui.QFrame.Panel)
        self.Cam3Name.setFrameShadow(QtGui.QFrame.Raised)
        self.Cam3Name.setObjectName(_fromUtf8("Cam3Name"))
        self.RecordingPathName3 = QtGui.QLabel(self.centralwidget)
        self.RecordingPathName3.setGeometry(QtCore.QRect(210, 388, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.RecordingPathName3.setFont(font)
        self.RecordingPathName3.setStyleSheet(_fromUtf8("background-color:rgb(200, 224, 255); color: rgb(0, 0, 0)"))
        self.RecordingPathName3.setFrameShape(QtGui.QFrame.Panel)
        self.RecordingPathName3.setFrameShadow(QtGui.QFrame.Raised)
        self.RecordingPathName3.setObjectName(_fromUtf8("RecordingPathName3"))
        self.idleChoice3 = QtGui.QLabel(self.centralwidget)
        self.idleChoice3.setGeometry(QtCore.QRect(500, 408, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.idleChoice3.setFont(font)
        self.idleChoice3.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.idleChoice3.setAlignment(QtCore.Qt.AlignCenter)
        self.idleChoice3.setObjectName(_fromUtf8("idleChoice3"))
        self.recordChoice3 = QtGui.QLabel(self.centralwidget)
        self.recordChoice3.setGeometry(QtCore.QRect(500, 388, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.recordChoice3.setFont(font)
        self.recordChoice3.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.recordChoice3.setAlignment(QtCore.Qt.AlignCenter)
        self.recordChoice3.setObjectName(_fromUtf8("recordChoice3"))
        self.growChoice1 = QtGui.QLabel(self.centralwidget)
        self.growChoice1.setGeometry(QtCore.QRect(570, 292, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.growChoice1.setFont(font)
        self.growChoice1.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.growChoice1.setAlignment(QtCore.Qt.AlignCenter)
        self.growChoice1.setObjectName(_fromUtf8("growChoice1"))
        self.notGrowingChoice1 = QtGui.QLabel(self.centralwidget)
        self.notGrowingChoice1.setGeometry(QtCore.QRect(570, 310, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.notGrowingChoice1.setFont(font)
        self.notGrowingChoice1.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.notGrowingChoice1.setAlignment(QtCore.Qt.AlignCenter)
        self.notGrowingChoice1.setObjectName(_fromUtf8("notGrowingChoice1"))
        self.growChoice2 = QtGui.QLabel(self.centralwidget)
        self.growChoice2.setGeometry(QtCore.QRect(570, 340, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.growChoice2.setFont(font)
        self.growChoice2.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.growChoice2.setAlignment(QtCore.Qt.AlignCenter)
        self.growChoice2.setObjectName(_fromUtf8("growChoice2"))
        self.notGrowingChoice2 = QtGui.QLabel(self.centralwidget)
        self.notGrowingChoice2.setGeometry(QtCore.QRect(570, 360, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.notGrowingChoice2.setFont(font)
        self.notGrowingChoice2.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.notGrowingChoice2.setAlignment(QtCore.Qt.AlignCenter)
        self.notGrowingChoice2.setObjectName(_fromUtf8("notGrowingChoice2"))
        self.growChoice3 = QtGui.QLabel(self.centralwidget)
        self.growChoice3.setGeometry(QtCore.QRect(570, 388, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.growChoice3.setFont(font)
        self.growChoice3.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.growChoice3.setAlignment(QtCore.Qt.AlignCenter)
        self.growChoice3.setObjectName(_fromUtf8("growChoice3"))
        self.notGrowingChoice3 = QtGui.QLabel(self.centralwidget)
        self.notGrowingChoice3.setGeometry(QtCore.QRect(570, 408, 66, 12))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.notGrowingChoice3.setFont(font)
        self.notGrowingChoice3.setStyleSheet(_fromUtf8("background:rgb(255,255,255);color:rgb(0,0,0)"))
        self.notGrowingChoice3.setAlignment(QtCore.Qt.AlignCenter)
        self.notGrowingChoice3.setObjectName(_fromUtf8("notGrowingChoice3"))
        CamDisplayMW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CamDisplayMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        CamDisplayMW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CamDisplayMW)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CamDisplayMW.setStatusBar(self.statusbar)

        self.retranslateUi(CamDisplayMW)
        QtCore.QMetaObject.connectSlotsByName(CamDisplayMW)

    def retranslateUi(self, CamDisplayMW):
        CamDisplayMW.setWindowTitle(QtGui.QApplication.translate("CamDisplayMW", "CamDisplay", None, QtGui.QApplication.UnicodeUTF8))
        self.ClockDisplay.setText(QtGui.QApplication.translate("CamDisplayMW", "SystemTime", None, QtGui.QApplication.UnicodeUTF8))
        self.Cam1Name.setText(QtGui.QApplication.translate("CamDisplayMW", "CamName", None, QtGui.QApplication.UnicodeUTF8))
        self.RecordingPathName1.setText(QtGui.QApplication.translate("CamDisplayMW", "RecordingPathName", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("CamDisplayMW", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.AltitudeDisplay.setText(QtGui.QApplication.translate("CamDisplayMW", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("CamDisplayMW", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("CamDisplayMW", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.clockLabeler.setText(QtGui.QApplication.translate("CamDisplayMW", "DateTime", None, QtGui.QApplication.UnicodeUTF8))
        self.altimeterChoice.setText(QtGui.QApplication.translate("CamDisplayMW", "Altimeter", None, QtGui.QApplication.UnicodeUTF8))
        self.dopplerChoice.setText(QtGui.QApplication.translate("CamDisplayMW", "Doppler", None, QtGui.QApplication.UnicodeUTF8))
        self.altitudeLabeler.setText(QtGui.QApplication.translate("CamDisplayMW", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.metaLabeler.setText(QtGui.QApplication.translate("CamDisplayMW", "Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.camSectionLabel.setText(QtGui.QApplication.translate("CamDisplayMW", "Cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.recordChoice1.setText(QtGui.QApplication.translate("CamDisplayMW", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.idleChoice1.setText(QtGui.QApplication.translate("CamDisplayMW", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.RecordingPathName2.setText(QtGui.QApplication.translate("CamDisplayMW", "RecordingPathName", None, QtGui.QApplication.UnicodeUTF8))
        self.Cam2Name.setText(QtGui.QApplication.translate("CamDisplayMW", "CamName", None, QtGui.QApplication.UnicodeUTF8))
        self.recordChoice2.setText(QtGui.QApplication.translate("CamDisplayMW", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.idleChoice2.setText(QtGui.QApplication.translate("CamDisplayMW", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.Cam3Name.setText(QtGui.QApplication.translate("CamDisplayMW", "CamName", None, QtGui.QApplication.UnicodeUTF8))
        self.RecordingPathName3.setText(QtGui.QApplication.translate("CamDisplayMW", "RecordingPathName", None, QtGui.QApplication.UnicodeUTF8))
        self.idleChoice3.setText(QtGui.QApplication.translate("CamDisplayMW", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.recordChoice3.setText(QtGui.QApplication.translate("CamDisplayMW", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.growChoice1.setText(QtGui.QApplication.translate("CamDisplayMW", "Growing", None, QtGui.QApplication.UnicodeUTF8))
        self.notGrowingChoice1.setText(QtGui.QApplication.translate("CamDisplayMW", "NotGrowing", None, QtGui.QApplication.UnicodeUTF8))
        self.growChoice2.setText(QtGui.QApplication.translate("CamDisplayMW", "Growing", None, QtGui.QApplication.UnicodeUTF8))
        self.notGrowingChoice2.setText(QtGui.QApplication.translate("CamDisplayMW", "NotGrowing", None, QtGui.QApplication.UnicodeUTF8))
        self.growChoice3.setText(QtGui.QApplication.translate("CamDisplayMW", "Growing", None, QtGui.QApplication.UnicodeUTF8))
        self.notGrowingChoice3.setText(QtGui.QApplication.translate("CamDisplayMW", "NotGrowing", None, QtGui.QApplication.UnicodeUTF8))

